hapi:
  fhir:
    version: r5
    server:
      path: /fhir/*
    rest:
      server-name: com.mdixinc.fhir.terminology
      server-version: 2.0.0
      implementation-description: MDIX FHIR Terminology Server
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.mdix: ${LOGGING_LEVEL_MDIX:TRACE}
    org.springframework: ${LOGGING_LEVEL_SPRING:info}
    com.google: ${LOGGING_LEVEL_JSCOMP:OFF}
   
